variables:
- name: BuildParameters.projectKey
  value: DevOps Project
- name: BuildParameters.projectName
  value: DevOps Project
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-18.04
  steps:
  - checkout: self
    clean: true
  
  - task: SonarCloudPrepare@1
    displayName: Prepare analysis on SonarCloud
    inputs:
      SonarCloud: d1013d03-3251-4984-b407-61023eddb10f
      organization: srivasarjit
      scannerMode: Other
      projectKey: $(BuildParameters.projectKey)
      projectName: $(BuildParameters.projectName)
      extraProperties: >-
        sonar.projectKey=srivasarjit_DevOps-Project

  - task: Maven@3
    displayName: Maven MyWebApp/pom.xml
    inputs:
      mavenPOMFile: pom.xml
  
  - task: SonarCloudAnalyze@1
    displayName: Run Code Analysis
  - task: SonarCloudPublish@1
    displayName: Publish Quality Gate Result
...
